### ISSUE TITLE
How to generate named functions per template

### ISSUE THREAD

**Issue by xavicolomer** [wix/gulp-react-templates#6]
I am using this template:

```
<h2>Hello world</h2>
```

Which Generates:

```
import React from 'react/addons';
import _ from 'lodash';
export default function () {
    return React.createElement('h2', {}, 'Hello world');
};
```

And this is how I would like to use it:

```
var Project = React.createClass({
    render: testRT
});
```

But I don't know how to set the testRT or other names to the generated templates. How should I do it?

Thanks

**Comment by ganimomer** [comment]
Hi,
If I understand your question correctly, you just want to name the generated template yourself in your class file.
This is as simple as using `import someName from 'hello.rt.js'` in your file, since the generated file has a default export.

[Here's](http://www.2ality.com/2014/09/es6-modules-final.html) a great article about this.
If I misunderstood your question, could you please clarify?

Thanks.

**Comment by xavicolomer** [comment]
The link you provided helped me figuring out how to import the templates. But now I have another issue, the templates are imported out of the scope.

```
import myTemplateRT from '../templates/myTemplate.rt.js';

(...)

let a = 'hello';
return myTemplateRT();
```

Template:

```
<h3>text: {a}</h3> 
```

Console:

```
Uncaught ReferenceError: a is not defined
```

This points to window, not to the object that called the function, any idea why that might be happening?

**Comment by xavicolomer** [comment]
For now I will be using:

```
myTemplateRT.apply(this)
```

**Comment by ganimomer** [comment]
Hi,
I answered this question in [this issue](https://github.com/wix/react-templates/issues/54#event-379267492) of the react-templates project itself.
Basically the *.rt.js file is its own module, so if you want to share data with it, you can assign a member or method to `this`, since it's applied with the same context.
